check, if dpg_type_partial is not None to void crash
It can happen the following while processing a dll:

AttributeError: 'NoneType' object has no attribute 'Unicode'

This is because __unpack_data__ can return None for whatever reason.